# Pandas Learning Practice
### Data Analysis & Data Handling | Notebook 02

## 1. Series and DataFrame

### Create a Pandas Series.

In [1]:
import pandas as pd
import numpy as np

sales_series = pd.Series([120, 150, 90, 200, 175], name="sales")
sales_series

0    120
1    150
2     90
3    200
4    175
Name: sales, dtype: int64

### Create a DataFrame.

In [2]:
df = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1008],
    "customer": ["Asha", "Ravi", "Meera", "Asha", "Kabir", "Nina", "Ravi", "Ira", "Ira"],
    "city": ["Ahmedabad", "Surat", "Ahmedabad", "Vadodara", "Surat", "Rajkot", "Ahmedabad", "Surat", "Surat"],
    "category": ["Electronics", "Home", "Books", "Books", "Electronics", "Home", "Books", "Electronics", "Electronics"],
    "quantity": [2, 1, 4, 3, 1, 2, 5, 1, 1],
    "unit_price": [1200., 850., 250., 300., 1500., 600., 280., 2100., 2100.],
    "order_date": ["2025-01-03", "2025-01-05", "2025-01-07", "2025-02-10", "2025-02-15", "2025-02-18", "2025-03-02", "2025-03-12", "2025-03-12"],
    "rating": [5, 4, np.nan, 4, 5, 3, 4, np.nan, np.nan],
    "discount_code": ["WELCOME", None, "BOOK10", None, "WELCOME", "HOME5", None, "TECH15", "TECH15"]
})
df

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Create a DataFrame with a custom index.

In [3]:
pd.DataFrame({"score": [82, 91, 76]}, index=["Asha", "Ravi", "Meera"])

       score
Asha      82
Ravi      91
Meera     76

## 2. Read and Write CSV, Excel, and JSON

### Write the sample DataFrame to CSV, Excel, and JSON.

In [4]:
df.to_csv("sales_data.csv", index=False)
df.to_excel("sales_data.xlsx", index=False)
df.to_json("sales_data.json", orient="records", indent=2)

### Read the CSV file.

In [5]:
pd.read_csv("sales_data.csv")

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Read the Excel file.

In [6]:
pd.read_excel("sales_data.xlsx")

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100,2025-03-12,NaN,TECH15

### Read the JSON file.

In [7]:
pd.read_json("sales_data.json")

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100,2025-03-12,NaN,TECH15

### Convert the first three rows to a JSON string.

In [8]:
df.head(3).to_json(orient="records", indent=2)

'[\n  {\n    "order_id":1001,\n    "customer":"Asha",\n    "city":"Ahmedabad",\n    "category":"Electronics",\n    "quantity":2,\n    "unit_price":1200.0,\n    "order_date":"2025-01-03",\n    "rating":5.0,\n    "discount_code":"WELCOME"\n  },\n  {\n    "order_id":1002,\n    "customer":"Ravi",\n    "city":"Surat",\n    "category":"Home",\n    "quantity":1,\n    "unit_price":850.0,\n    "order_date":"2025-01-05",\n    "rating":4.0,\n    "discount_code":null\n  },\n  {\n    "order_id":1003,\n    "customer":"Meera",\n    "city":"Ahmedabad",\n    "category":"Books",\n    "quantity":4,\n    "unit_price":250.0,\n    "order_date":"2025-01-07",\n    "rating":null,\n    "discount_code":"BOOK10"\n  }\n]'

## 3. Inspecting Data and Data Types

### Display the first five rows.

In [9]:
df.head()

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME

### Display the last three rows.

In [10]:
df.tail(3)

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Find the row and column count.

In [11]:
df.shape

(9, 9)

### Inspect column data types.

In [12]:
df.dtypes

order_id           int64
customer             str
city                 str
category             str
quantity           int64
unit_price       float64
order_date           str
rating           float64
discount_code        str
dtype: object

### Display concise DataFrame information.

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       9 non-null      int64
 1   customer       9 non-null      str
 2   city           9 non-null      str
 3   category       9 non-null      str
 4   quantity       9 non-null      int64
 5   unit_price     9 non-null      float64
 6   order_date     9 non-null      str
 7   rating         6 non-null      float64
 8   discount_code  6 non-null      str
dtypes: float64(2), int64(2), str(5)
memory usage: 1.0 KB

### Generate numerical descriptive statistics.

In [14]:
df.describe()

          order_id  quantity   unit_price    rating
count     9.000000  9.000000     9.000000  6.000000
mean   1004.888889  2.222222  1020.000000  4.166667
std       2.571208  1.481366   746.642485  0.752773
min    1001.000000  1.000000   250.000000  3.000000
25%    1003.000000  1.000000   300.000000  4.000000
50%    1005.000000  2.000000   850.000000  4.000000
75%    1007.000000  3.000000  1500.000000  4.750000
max    1008.000000  5.000000  2100.000000  5.000000

### Count missing values in each column.

In [15]:
df.isna().sum()

order_id         0
customer         0
city             0
category         0
quantity         0
unit_price       0
order_date       0
rating           3
discount_code    3
dtype: int64

## 4. Selecting Rows and Columns

### Select the customer column as a Series.

In [16]:
df["customer"]

0     Asha
1     Ravi
2    Meera
3     Asha
4    Kabir
5     Nina
6     Ravi
7      Ira
8      Ira
Name: customer, dtype: str

### Select customer and category columns.

In [17]:
df[["customer", "category"]]

  customer     category
0     Asha  Electronics
1     Ravi         Home
2    Meera        Books
3     Asha        Books
4    Kabir  Electronics
5     Nina         Home
6     Ravi        Books
7      Ira  Electronics
8      Ira  Electronics

### Select the first three rows by position.

In [18]:
df.iloc[:3]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10

### Select the first three rows and first four columns.

In [19]:
df.iloc[:3, :4]

   order_id customer       city     category
0      1001     Asha  Ahmedabad  Electronics
1      1002     Ravi      Surat         Home
2      1003    Meera  Ahmedabad        Books

### Select rows with index labels 2 through 5.

In [20]:
df.loc[2:5, ["customer", "city", "category"]]

  customer       city     category
2    Meera  Ahmedabad        Books
3     Asha   Vadodara        Books
4    Kabir      Surat  Electronics
5     Nina     Rajkot         Home

## 5. Filtering and Sorting

### Find orders with quantity greater than 2.

In [21]:
df[df["quantity"] > 2]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN

### Find orders from Ahmedabad.

In [22]:
df[df["city"] == "Ahmedabad"]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN

### Find Electronics orders priced above 1000.

In [23]:
df[(df["category"] == "Electronics") & (df["unit_price"] > 1000)]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Find orders from Ahmedabad or Surat.

In [24]:
df[df["city"].isin(["Ahmedabad", "Surat"])]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Sort orders by unit price from highest to lowest.

In [25]:
df.sort_values("unit_price", ascending=False)

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10

### Sort by city and then order date.

In [26]:
df.sort_values(["city", "order_date"])

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN

## 6. Missing-Value Detection and Handling

### Find rows with at least one missing value.

In [27]:
df[df.isna().any(axis=1)]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Fill missing ratings with the median rating.

In [28]:
df.assign(rating=df["rating"].fillna(df["rating"].median()))

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,4.0,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,4.0,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,4.0,TECH15

### Fill missing discount codes with NO_DISCOUNT.

In [29]:
df.assign(discount_code=df["discount_code"].fillna("NO_DISCOUNT"))

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NO_DISCOUNT
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NO_DISCOUNT
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NO_DISCOUNT
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Drop rows where rating is missing.

In [30]:
df.dropna(subset=["rating"])

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN

### Drop columns containing any missing values.

In [31]:
df.dropna(axis=1)

   order_id customer       city     category  quantity  unit_price  order_date
0      1001     Asha  Ahmedabad  Electronics         2      1200.0  2025-01-03
1      1002     Ravi      Surat         Home         1       850.0  2025-01-05
2      1003    Meera  Ahmedabad        Books         4       250.0  2025-01-07
3      1004     Asha   Vadodara        Books         3       300.0  2025-02-10
4      1005    Kabir      Surat  Electronics         1      1500.0  2025-02-15
5      1006     Nina     Rajkot         Home         2       600.0  2025-02-18
6      1007     Ravi  Ahmedabad        Books         5       280.0  2025-03-02
7      1008      Ira      Surat  Electronics         1      2100.0  2025-03-12
8      1008      Ira      Surat  Electronics         1      2100.0  2025-03-12

## 7. Duplicate Detection and Removal

### Find duplicated rows.

In [32]:
df[df.duplicated()]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Count fully duplicated rows.

In [33]:
df.duplicated().sum()

np.int64(1)

### Remove fully duplicated rows.

In [34]:
df.drop_duplicates()

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Remove duplicate order IDs, keeping the first occurrence.

In [35]:
df.drop_duplicates(subset=["order_id"], keep="first")

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

## 8. GroupBy and Aggregation

### Calculate total quantity and average price by category.

In [36]:
df.groupby("category").agg(total_quantity=("quantity", "sum"), average_price=("unit_price", "mean"))

             total_quantity  average_price
category
Books                    12     276.666667
Electronics               5    1725.000000
Home                      3     725.000000

### Calculate order count and total revenue by city.

In [37]:
df.assign(revenue=df["quantity"] * df["unit_price"]).groupby("city").agg(order_count=("order_id", "count"), total_revenue=("revenue", "sum"))

           order_count  total_revenue
city
Ahmedabad            3         4800.0
Rajkot               1         1200.0
Surat                4         6550.0
Vadodara             1          900.0

### Calculate total quantity by city and category.

In [38]:
df.groupby(["city", "category"])["quantity"].sum()

city       category
Ahmedabad  Books          9
           Electronics    2
Rajkot     Home           2
Surat      Electronics    3
           Home           1
Vadodara   Books          3
Name: quantity, dtype: int64

### Find the category with the highest total quantity.

In [39]:
df.groupby("category")["quantity"].sum().idxmax()

'Books'

### Calculate min, max, mean, and median unit price by category.

In [40]:
df.groupby("category")["unit_price"].agg(["min", "max", "mean", "median"])

                min     max         mean  median
category
Books         250.0   300.0   276.666667   280.0
Electronics  1200.0  2100.0  1725.000000  1800.0
Home          600.0   850.0   725.000000   725.0

## 9. Merge, Join, and Concatenation

### Merge orders with a customer membership table.

In [41]:
customer_info = pd.DataFrame({
    "customer": ["Asha", "Ravi", "Meera", "Kabir", "Nina", "Ira"],
    "membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
df.merge(customer_info, on="customer", how="left")

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code,membership
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME,Gold
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN,Silver
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10,Gold
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN,Gold
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME,Bronze
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5,Silver
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN,Silver
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,Gold
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,Gold

### Join two DataFrames using their index.

In [42]:
left = pd.DataFrame({"customer": ["Asha", "Ravi"]}, index=[1, 2])
right = pd.DataFrame({"membership": ["Gold", "Silver"]}, index=[1, 2])
left.join(right)

  customer membership
1     Asha       Gold
2     Ravi     Silver

### Concatenate DataFrames vertically.

In [43]:
jan = pd.DataFrame({"month": ["Jan"], "sales": [1200]})
feb = pd.DataFrame({"month": ["Feb"], "sales": [1500]})
pd.concat([jan, feb], ignore_index=True)

  month  sales
0   Jan   1200
1   Feb   1500

### Concatenate DataFrames horizontally.

In [44]:
pd.concat([left.reset_index(drop=True), right.reset_index(drop=True)], axis=1)

  customer membership
0     Asha       Gold
1     Ravi     Silver

## 10. Date/Time Data

### Convert order_date to Pandas datetime.

In [45]:
df.assign(order_date=pd.to_datetime(df["order_date"]))

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Extract year, month, and day.

In [46]:
dates = pd.to_datetime(df["order_date"])
pd.DataFrame({"year": dates.dt.year, "month": dates.dt.month, "day": dates.dt.day})

   year  month  day
0  2025      1    3
1  2025      1    5
2  2025      1    7
3  2025      2   10
4  2025      2   15
5  2025      2   18
6  2025      3    2
7  2025      3   12
8  2025      3   12

### Filter orders placed during February 2025.

In [47]:
df[pd.to_datetime(df["order_date"]).dt.month == 2]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5

### Find days since the earliest order.

In [48]:
(pd.to_datetime(df["order_date"]) - pd.to_datetime(df["order_date"]).min()).dt.days

0     0
1     2
2     4
3    38
4    43
5    46
6    58
7    68
8    68
Name: order_date, dtype: int64

### Resample revenue into monthly totals.

In [49]:
daily_revenue = df.assign(
    order_date=pd.to_datetime(df["order_date"]),
    revenue=df["quantity"] * df["unit_price"]
).set_index("order_date")["revenue"]
daily_revenue.resample("MS").sum()

order_date
2025-01-01    4250.0
2025-02-01    3600.0
2025-03-01    5600.0
Freq: MS, Name: revenue, dtype: float64

## 11. String and Categorical Operations

### Convert customer names to uppercase.

In [50]:
df["customer"].str.upper()

0     ASHA
1     RAVI
2    MEERA
3     ASHA
4    KABIR
5     NINA
6     RAVI
7      IRA
8      IRA
Name: customer, dtype: str

### Find customer names containing 'a', case-insensitively.

In [51]:
df[df["customer"].str.contains("a", case=False, na=False)]

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15

### Remove leading and trailing whitespace from strings.

In [52]:
pd.Series(["  Ahmedabad ", " Surat", "Rajkot  "]).str.strip()

0    Ahmedabad
1        Surat
2       Rajkot
dtype: str

### Convert category to a categorical data type.

In [53]:
df.assign(category=df["category"].astype("category")).dtypes

order_id            int64
customer              str
city                  str
category         category
quantity            int64
unit_price        float64
order_date            str
rating            float64
discount_code         str
dtype: object

### Count occurrences of each category.

In [54]:
df["category"].value_counts()

category
Electronics    4
Books          3
Home           2
Name: count, dtype: int64

### Replace Home with Home & Living.

In [55]:
df["category"].replace({"Home": "Home & Living"})

0      Electronics
1    Home & Living
2            Books
3            Books
4      Electronics
5    Home & Living
6            Books
7      Electronics
8      Electronics
Name: category, dtype: str

## 12. Apply, Map, and Vectorized Operations

### Calculate revenue using vectorized multiplication.

In [56]:
df.assign(revenue=df["quantity"] * df["unit_price"])

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code,revenue
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME,2400.0
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN,850.0
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10,1000.0
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN,900.0
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME,1500.0
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5,1200.0
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN,1400.0
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,2100.0
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,2100.0

### Map categories to department codes.

In [57]:
df["category"].map({"Electronics": "ELEC", "Home": "HOME", "Books": "BOOKS"})

0     ELEC
1     HOME
2    BOOKS
3    BOOKS
4     ELEC
5     HOME
6    BOOKS
7     ELEC
8     ELEC
Name: category, dtype: str

### Apply a 10% price increase to each unit price.

In [58]:
df["unit_price"].apply(lambda price: price * 1.10)

0    1320.0
1     935.0
2     275.0
3     330.0
4    1650.0
5     660.0
6     308.0
7    2310.0
8    2310.0
Name: unit_price, dtype: float64

### Label orders as Large or Small using vectorized conditional logic.

In [59]:
df.assign(order_size=np.where(df["quantity"] >= 3, "Large", "Small"))

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code,order_size
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME,Small
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN,Small
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10,Large
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN,Large
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME,Small
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5,Small
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN,Large
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,Small
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,Small

### Calculate revenue and flag orders above 1000.

In [60]:
df.assign(revenue=df["quantity"] * df["unit_price"], high_value=(df["quantity"] * df["unit_price"]) > 1000)

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code,revenue,high_value
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME,2400.0,True
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NaN,850.0,False
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,NaN,BOOK10,1000.0,False
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NaN,900.0,False
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME,1500.0,True
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5,1200.0,True
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NaN,1400.0,True
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,2100.0,True
8,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,NaN,TECH15,2100.0,True

## 13. Export Cleaned Data

### Create cleaned data with unique order IDs, filled missing values, revenue, and datetime.

In [61]:
cleaned_df = (
    df.drop_duplicates(subset=["order_id"], keep="first")
      .assign(
          rating=lambda data: data["rating"].fillna(data["rating"].median()),
          discount_code=lambda data: data["discount_code"].fillna("NO_DISCOUNT"),
          revenue=lambda data: data["quantity"] * data["unit_price"],
          order_date=lambda data: pd.to_datetime(data["order_date"])
      )
)
cleaned_df

,order_id,customer,city,category,quantity,unit_price,order_date,rating,discount_code,revenue
0,1001,Asha,Ahmedabad,Electronics,2,1200.0,2025-01-03,5.0,WELCOME,2400.0
1,1002,Ravi,Surat,Home,1,850.0,2025-01-05,4.0,NO_DISCOUNT,850.0
2,1003,Meera,Ahmedabad,Books,4,250.0,2025-01-07,4.0,BOOK10,1000.0
3,1004,Asha,Vadodara,Books,3,300.0,2025-02-10,4.0,NO_DISCOUNT,900.0
4,1005,Kabir,Surat,Electronics,1,1500.0,2025-02-15,5.0,WELCOME,1500.0
5,1006,Nina,Rajkot,Home,2,600.0,2025-02-18,3.0,HOME5,1200.0
6,1007,Ravi,Ahmedabad,Books,5,280.0,2025-03-02,4.0,NO_DISCOUNT,1400.0
7,1008,Ira,Surat,Electronics,1,2100.0,2025-03-12,4.0,TECH15,2100.0

### Export cleaned data to CSV.

In [62]:
cleaned_df.to_csv("cleaned_sales_data.csv", index=False)

### Export cleaned data to Excel.

In [63]:
cleaned_df.to_excel("cleaned_sales_data.xlsx", index=False)

### Export cleaned data to JSON records.

In [64]:
cleaned_df.to_json("cleaned_sales_data.json", orient="records", date_format="iso", indent=2)

### Verify duplicate IDs and missing values in key columns.

In [65]:
{"duplicate_order_ids": cleaned_df["order_id"].duplicated().sum(), "missing_customer": cleaned_df["customer"].isna().sum(), "missing_revenue": cleaned_df["revenue"].isna().sum()}

{'duplicate_order_ids': np.int64(0),
 'missing_customer': np.int64(0),
 'missing_revenue': np.int64(0)}